const pool = require('../config/database');
const HttpError = require('../utils/httpError');

// Course completion certificates.
//
// "Completed" is the existing definition: an enrolment whose status is 'completed' (the
// course has topics and the student finished all of them). A certificate is issued the
// moment an enrolment BECOMES completed, inside the same transaction as the status change,
// so completion and certificate never disagree. Issuing is idempotent: the database allows
// one certificate per (student, course) and the insert ignores that conflict.
// Certificate numbers are generated by the database and never come from a client.
//
// Enrolments that were already completed before certificates existed are left alone
// (nothing is back-filled automatically).

// `db` is the pool or a transaction client; `enrolmentIds` are enrolments that have just
// become completed. Only Students receive certificates (a user later made Trainer/Admin
// does not get new ones). Returns the number of certificates created.
async function issueForEnrolments(db, enrolmentIds) {
  if (enrolmentIds.length === 0) return 0;
  const { rowCount } = await db.query(
    `INSERT INTO certificates (student_id, course_id, student_name, course_title)
     SELECT e.student_id, e.course_id, u.full_name, c.title
     FROM enrolments e
     JOIN users u ON u.id = e.student_id AND u.role = 'student'
     JOIN courses c ON c.id = e.course_id
     WHERE e.id = ANY($1::bigint[]) AND e.status = 'completed'
     ON CONFLICT (student_id, course_id) DO NOTHING`,
    [enrolmentIds]
  );
  return rowCount;
}

const SELECT = `
  SELECT ct.id, ct.certificate_number, ct.student_id, ct.course_id, ct.student_name, ct.course_title,
         ct.issued_at, ct.status, ct.revoked_at, ct.revocation_reason,
         u.email AS student_email, rb.full_name AS revoked_by_name
  FROM certificates ct
  JOIN users u ON u.id = ct.student_id
  LEFT JOIN users rb ON rb.id = ct.revoked_by`;

// What a Student (or anyone printing it) sees: the issued facts and the status. The
// revocation reason and who revoked are for Admin only.
function toCertificate(row) {
  return {
    id: row.id,
    certificateNumber: row.certificate_number,
    studentName: row.student_name,
    courseTitle: row.course_title,
    issuedAt: row.issued_at,
    status: row.status,
    revokedAt: row.revoked_at,
  };
}

function toAdminCertificate(row) {
  return {
    ...toCertificate(row),
    studentId: row.student_id,
    studentEmail: row.student_email,
    courseId: row.course_id,
    revokedByName: row.revoked_by_name,
    revocationReason: row.revocation_reason,
  };
}

// ---------------------------------------------------------------------------
// Student: always the signed-in student; another student's id looks like "not found".
// ---------------------------------------------------------------------------

async function listForStudent(studentId) {
  const { rows } = await pool.query(`${SELECT} WHERE ct.student_id = $1 ORDER BY ct.issued_at DESC, ct.id DESC`, [studentId]);
  return rows.map(toCertificate);
}

async function getForStudent(studentId, id) {
  const { rows } = await pool.query(`${SELECT} WHERE ct.id = $1 AND ct.student_id = $2`, [id, studentId]);
  if (!rows[0]) throw new HttpError(404, 'Certificate not found');
  return toCertificate(rows[0]);
}

// The student's certificate for a course, if any (shown on the learning page).
async function findForStudentCourse(studentId, courseId, db = pool) {
  const { rows } = await db.query('SELECT id, certificate_number, status FROM certificates WHERE student_id = $1 AND course_id = $2', [
    studentId,
    courseId,
  ]);
  return rows[0] ? { id: rows[0].id, certificateNumber: rows[0].certificate_number, status: rows[0].status } : null;
}

// ---------------------------------------------------------------------------
// Admin
// ---------------------------------------------------------------------------

async function listForAdmin({ courseId, studentId, status } = {}) {
  const where = [];
  const params = [];
  if (courseId) {
    params.push(courseId);
    where.push(`ct.course_id = $${params.length}`);
  }
  if (studentId) {
    params.push(studentId);
    where.push(`ct.student_id = $${params.length}`);
  }
  if (status) {
    params.push(status);
    where.push(`ct.status = $${params.length}`);
  }
  const { rows } = await pool.query(
    `${SELECT} ${where.length ? `WHERE ${where.join(' AND ')}` : ''} ORDER BY ct.issued_at DESC, ct.id DESC`,
    params
  );
  return rows.map(toAdminCertificate);
}

async function getForAdmin(id) {
  const { rows } = await pool.query(`${SELECT} WHERE ct.id = $1`, [id]);
  if (!rows[0]) throw new HttpError(404, 'Certificate not found');
  return toAdminCertificate(rows[0]);
}

// Revocation keeps the certificate; it records who, when and why. It cannot be undone.
async function revoke(adminId, id, reason) {
  const { rows } = await pool.query(
    `UPDATE certificates SET status = 'revoked', revoked_at = now(), revoked_by = $2, revocation_reason = $3
     WHERE id = $1 AND status = 'active' RETURNING id`,
    [id, adminId, reason]
  );
  if (!rows[0]) {
    await getForAdmin(id); // 404 when it does not exist
    throw new HttpError(409, 'This certificate is already revoked');
  }
  return getForAdmin(id);
}

module.exports = {
  issueForEnrolments,
  listForStudent,
  getForStudent,
  findForStudentCourse,
  listForAdmin,
  getForAdmin,
  revoke,
};
