import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  BookOpen,
  BrainCircuit,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clock,
  Code2,
  FolderOpen,
  Globe,
  GraduationCap,
  Layers,
  LayoutGrid,
  ListTree,
  LogOut,
  Menu,
  Palette,
  PlayCircle,
  Sparkles,
  Target,
  User,
  Users,
  Video,
  VideoOff,
  WandSparkles,
  X,
} from 'lucide-react'

// One icon system (Lucide). Names are the ones used across the app.
const ICONS = {
  book: BookOpen,
  clock: Clock,
  level: BarChart3,
  user: User,
  users: Users,
  calendar: CalendarDays,
  video: Video,
  videoOff: VideoOff,
  play: PlayCircle,
  check: Check,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  logout: LogOut,
  menu: Menu,
  close: X,
  target: Target,
  grid: LayoutGrid,
  layers: Layers,
  sparkles: Sparkles,
  code: Code2,
  cap: GraduationCap,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  // Course-level icons (see utils/courseVisual.js)
  chart: BarChart3,
  brain: BrainCircuit,
  wand: WandSparkles,
  globe: Globe,
  briefcase: BriefcaseBusiness,
  palette: Palette,
  // Learning page: topic states and course outline
  topicDone: CheckCircle2,
  topicCurrent: PlayCircle,
  topicOpen: Circle,
  module: FolderOpen,
  outline: ListTree,
}

export function Icon({ name, size = 18, className }) {
  const Component = ICONS[name]
  if (!Component) return null
  return <Component className={className} size={size} strokeWidth={2} aria-hidden="true" focusable="false" />
}
